import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from "../styles/Home.module.css"
import Form from "../pages/components/form.js"
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title> Building On Imagination</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          
          <div>
          
          </div>
        </div>

        <div className={styles.center}>
          <div className={styles.thirteen}>
           <div className='inner_card inner_card_what'>
              <h2 className={inter.className}>What is Building On Imagination?</h2>
                <p className={inter.className}>Learn more about the project and idea behind it.</p>
                <a target="_blink" href='https://boimagination.substack.com/p/building-on-imagination' className={inter.className}>Read more</a>
           </div>
          </div>
          <div className={ `${styles.thirteen} ${styles.thirteen_form}`}>
          <div className='inner_card'>
          <Image
              src="/boi.svg"
              alt="13"
              width={56}
              height={31}
            className="logo"
            /> 
            <span>Join My Newsletter</span>
              <h3 className={inter.className}>Building On Imagination.</h3>
                <p className={inter.className}>Exploring and transforming ideas into reality.</p>
                <div>
               <Form />
                </div>
           </div>
          </div>
        </div>

        <div className={`${styles.grid} ${styles.links}`}>
          <a
            href="https://mohamedsadiq.me"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Site 
            </h2>
          
          </a>

          <a
            href="https://twitter.com/sadiq_moo"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Twitter
            </h2>
          
          </a>

          <a
            href="https://github.com/mohamedsadiq"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>Github</h2>
           
          </a>

          <a
            href="https://boimagination.substack.com/p/building-on-imagination"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
            Blog 
            </h2>
           
          </a>
        </div>
      </main>
    </>
  )
}

